### ISSUE TITLE
🖐️

### ISSUE THREAD

**Issue by HySuren** [Kobanoss/HEXAGON-TT#1]
Приветствую вас Владимир Олегович, не думал что вы используете FaspAPI😁

Обычно всегда писали на flask)

**Comment by Kobanoss** [comment]
Я плююсь только в сторону Django)
Хотя даже на нем приходилось пару проектов писать

**Comment by HySuren** [comment]
Я знаю)

**Comment by Kobanoss** [comment]
> Я знаю)

Как у самого вообще дела?)

**Comment by HySuren** [comment]
> > Я знаю)
> 
> Как у самого вообще дела?)

Так по тихоньку, в поисках ворка))

**Comment by HySuren** [comment]
> > > Я знаю)
> > 
> > Как у самого вообще дела?)
> 
> Так по тихоньку, в поисках ворка))

А так все нормально, с учёбой само собой тоже)

**Comment by Kobanoss** [comment]
> > > > Я знаю)
> > > 
> > > Как у самого вообще дела?)
> > 
> > Так по тихоньку, в поисках ворка))
> 
> А так все нормально, с учёбой само собой тоже)

Рад слышать, что твои стремления со времён колледжа лишь укрепились)

Где сейчас учишься?

**Comment by HySuren** [comment]
> > > > > Я знаю)
> > > > 
> > > > Как у самого вообще дела?)
> > > 
> > > Так по тихоньку, в поисках ворка))
> > 
> > А так все нормально, с учёбой само собой тоже)
> 
> Рад слышать, что твои стремления со времён колледжа лишь укрепились)
> 
> Где сейчас учишься?

Спасибо)
Пока к сожалению ещё там же)
Последний курс, после планировал поступить в Бауманку, либо же ДВФУ

Там уже как получится

**Comment by HySuren** [comment]
А чем вы сейчас чем занимаетесь?

**Comment by Kobanoss** [comment]
> > > > > > Я знаю)
> > > > > 
> > > > > Как у самого вообще дела?)
> > > > 
> > > > Так по тихоньку, в поисках ворка))
> > > 
> > > А так все нормально, с учёбой само собой тоже)
> > 
> > Рад слышать, что твои стремления со времён колледжа лишь укрепились)
> > 
> > Где сейчас учишься?
> 
> Спасибо)
> Пока к сожалению ещё там же)
> Последний курс, после планировал поступить в Бауманку, либо же ДВФУ
> 
> Там уже как получится


У меня за последнее время столько всякого произошло, что думал, что уж больше времени прошло.

Разброс конечно сильный по карте)
Ну, если решишь поступать в Бауманку, то может и свидимся ещё очно)

А сам я сейчас допиливаю универ, так сказать, работаю потихоньку, недавно на новое место устроился.

Пиши, как у вас защиты и вручение будут, может забегу посмотреть на вас, уже совсем взрослые господа, все же)

**Comment by HySuren** [comment]
Рад за вас)
Надеюсь вам нравится новое место работы

Пр поводу Бауманки, в принципе в первую очередь постараюсь поступить в нее.

Хорошо, я не забуду написать после защиты;)

**Comment by HySuren** [comment]
Доброе утро)
Извеняюсь что пишу тут, просто потерял старый тг ак...
Можете дать пару коментариев по поводу того как оформлен readme.md и что можно улучшить https://github.com/HySuren/Restoran_SYSTEM

Просто этот проект хочу представлять в резюме, вот и парюсь
